export const skillsData = [
    "Semantic & accessible HTML",
    "Responsive Web Design",
    "Teamwork",
    "Markdown",
    "Immutability",
    "CSS BEM convention",
    "CSS Grid",
    "CSS Flexbox",
    "React Router",
    "Redux-Saga",
    "Redux (Toolkit)",
    "React Hooks",
    "Error handling",
    "Working with API (fetch, axios)",
    "JavaScript: ES6+",
    "Promises, Async/Await",
    "Github Pull Requests & Review",
    "Trello",
    "Scrum",
    "NPM",
    "React",
    "Git",
    "Adobe Photoshop",
    "Adobe InDesign",
    "Adobe Illustrator",
    "Adobe Premiere Pro",
    "Adobe Creative Cloud",
];

export const futureSkillsData = [
    "Typescript",
    "React Native",
    "React Context",
    "JS Classes",
    "Unit testing",
];